<a href="https://colab.research.google.com/github/KritishBokde91/NNDL_LAB/blob/main/NNDL_PRACTICAL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
!pip install numpy pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [29]:
import numpy as np
import pandas as pd
from google.colab import drive, files
import io

In [6]:
#Vector Addition
vector1 = np.array([5, 10, 15])
vector2 = np.array([1, 8, 21])

result1 = vector1 + vector2
print(result1)

[ 6 18 36]

In [13]:
#Vector Multiplication
vector3 = np.array([[15, 30, 16], [25, 50, 27], [12, 18, 40]])
vector4 = np.array([[1, 16, 25], [88, 76, 4], [18, 36, 77]])

result2 = np.matmul(vector3, vector4)
print(result2)

[[2943 3096 1727]
 [4911 5172 2904]
 [2316 3000 3452]]

In [18]:
#Read CSV File using Pandas
data = pd.read_csv("/content/sample_data/movie_dataset.csv")
data.head()

,id,title,original_language,original_title,overview,release_date,popularity,vote_count,rating
0,13448,Angels & Demons,en,Angels & Demons,Harvard symbologist Robert Langdon is recruite...,2009-04-20,6.8861,7323,6.719
1,9603,Clueless,en,Clueless,"Shallow, rich and socially successful Cher is ...",1995-07-19,7.5190,4801,7.255
2,6557,27 Dresses,en,27 Dresses,Altruistic Jane finds herself facing her worst...,2008-01-10,5.7786,3421,6.453
3,1333100,Attack on Titan: THE LAST ATTACK,ja,劇場版「進撃の巨人」完結編 THE LAST ATTACK,A colossal-sized omnibus film bringing togethe...,2024-03-20,6.0979,205,8.700
4,578701,Those Who Wish Me Dead,en,Those Who Wish Me Dead,A young boy finds himself pursued by two assas...,2021-05-05,6.2045,1849,6.607

In [21]:
#Read CSV File using Drive
drive.mount("/content/drive")
dataset = pd.read_csv('/content/drive/MyDrive/NNDL_LAB/movie_dataset.csv')
dataset.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,id,title,original_language,original_title,overview,release_date,popularity,vote_count,rating
0,13448,Angels & Demons,en,Angels & Demons,Harvard symbologist Robert Langdon is recruite...,2009-04-20,6.8861,7323,6.719
1,9603,Clueless,en,Clueless,"Shallow, rich and socially successful Cher is ...",1995-07-19,7.5190,4801,7.255
2,6557,27 Dresses,en,27 Dresses,Altruistic Jane finds herself facing her worst...,2008-01-10,5.7786,3421,6.453
3,1333100,Attack on Titan: THE LAST ATTACK,ja,劇場版「進撃の巨人」完結編 THE LAST ATTACK,A colossal-sized omnibus film bringing togethe...,2024-03-20,6.0979,205,8.700
4,578701,Those Who Wish Me Dead,en,Those Who Wish Me Dead,A young boy finds himself pursued by two assas...,2021-05-05,6.2045,1849,6.607

In [34]:
#Read CSV File using Python Files
uploaded = files.upload()
data2 = pd.read_csv("/content/movie_dataset.csv")
data2.head()

Saving movie_dataset.csv to movie_dataset (1).csv

,id,title,original_language,original_title,overview,release_date,popularity,vote_count,rating
0,13448,Angels & Demons,en,Angels & Demons,Harvard symbologist Robert Langdon is recruite...,2009-04-20,6.8861,7323,6.719
1,9603,Clueless,en,Clueless,"Shallow, rich and socially successful Cher is ...",1995-07-19,7.5190,4801,7.255
2,6557,27 Dresses,en,27 Dresses,Altruistic Jane finds herself facing her worst...,2008-01-10,5.7786,3421,6.453
3,1333100,Attack on Titan: THE LAST ATTACK,ja,劇場版「進撃の巨人」完結編 THE LAST ATTACK,A colossal-sized omnibus film bringing togethe...,2024-03-20,6.0979,205,8.700
4,578701,Those Who Wish Me Dead,en,Those Who Wish Me Dead,A young boy finds himself pursued by two assas...,2021-05-05,6.2045,1849,6.607

In [ ]:
#Read CSV File using Kaggle Dataset